/* Launch! Calculator accessory. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ACCLIB.H"
static const char *keys[17]={"7","8","9","-","%","4","5","6","/","1","2","3","+","*","0",".","="};
static const char *labels[17]={"7","8","9","-","%","4","5","6","\366","1","2","3","+","x","0",".","="};
static const int ky[17]={0,0,0,0,0,3,3,3,3,6,6,6,6,6,9,9,9};
static const int kx[17]={0,6,12,20,26,0,6,12,26,0,6,12,20,26,0,12,26};
static void output_box(int x,int y,int w,double v,const char *entry){char s[40];int i;if(entry&&*entry)strncpy(s,entry,39);else sprintf(s,"%.10g",v);s[39]=0;for(i=0;i<w-2;i++)acc_put(x+1+i,y+1,' ',0x0A);acc_text(x+w-1-(int)strlen(s),y+1,s,0x0A,(int)strlen(s));for(i=1;i<w-1;i++){acc_put(x+i,y,196,ACC_BORDER);acc_put(x+i,y+2,196,ACC_BORDER);}acc_put(x,y,218,ACC_BORDER);acc_put(x+w-1,y,191,ACC_BORDER);acc_put(x,y+1,179,ACC_BORDER);acc_put(x+w-1,y+1,179,ACC_BORDER);acc_put(x,y+2,192,ACC_BORDER);acc_put(x+w-1,y+2,217,ACC_BORDER);}
static void frame(int x,int y,int w,int h,const char *s,int focus,int plus){int i,j,a=ACC_ATTR(acc_appearance.background,focus?acc_appearance.labels:(plus?acc_appearance.titles:acc_appearance.launchers));int hz=196,vt=179,tl=218,tr=191,bl=192,br=217;acc_fill(x,y,w,h,' ',ACC_BG);acc_put(x,y,tl,a);acc_put(x+w-1,y,tr,a);acc_put(x,y+h-1,bl,a);acc_put(x+w-1,y+h-1,br,a);for(i=1;i<w-1;i++){acc_put(x+i,y,hz,a);acc_put(x+i,y+h-1,hz,a);}for(j=1;j<h-1;j++){acc_put(x,y+j,vt,a);acc_put(x+w-1,y+j,vt,a);}acc_text(x+(w-(int)strlen(s))/2,y+h/2,s,a,(int)strlen(s));}
static void draw_keys(int x,int y,int focus){int i;for(i=0;i<17;i++){if(i==3||i==12)frame(x+kx[i],y+ky[i],5,6,labels[i],focus==i,i==12);else if(i==14)frame(x,y+9,11,3,"0",focus==i,0);else frame(x+kx[i],y+ky[i],5,3,labels[i],focus==i,0);}}
static int key_index(int ch){int i;for(i=0;i<17;i++)if(keys[i][0]==ch&&keys[i][1]==0)return i;return-1;}
static void flash_key(int x,int y,int index,int restore){unsigned long t;if(index<0)return;draw_keys(x,y,index);t=acc_ticks();while(acc_ticks()==t);t=acc_ticks();while(acc_ticks()==t);draw_keys(x,y,restore);}
static int move_key(int focus,int key){int i,best=focus,bestscore=32767,fx,fy,ix,iy,dx,dy,score;if(focus<0||focus>=17)return 0;fx=kx[focus]+((focus==14)?5:2);fy=ky[focus]+((focus==3||focus==12)?2:1);for(i=0;i<17;i++){if(i==focus)continue;ix=kx[i]+((i==14)?5:2);iy=ky[i]+((i==3||i==12)?2:1);dx=ix-fx;dy=iy-fy;if((key==256+75&&dx>=0)||(key==256+77&&dx<=0)||(key==256+72&&dy>=0)||(key==256+80&&dy<=0))continue;score=(key==256+75||key==256+77)?(abs(dx)*100+abs(dy)):(abs(dy)*100+abs(dx));if(score<bestscore){bestscore=score;best=i;}}return best;}
static void apply(const char *s,double *v,char *entry,char *op){double n;if(strlen(s)==1&&((*s>='0'&&*s<='9')||*s=='.')){if(strlen(entry)<20&&(*s!='.'||!strchr(entry,'.'))){entry[strlen(entry)+1]=0;entry[strlen(entry)]=*s;}return;}n=*entry?atof(entry):*v;if(!strcmp(s,"%")){n/=100.0;*v=n;*entry=0;return;}if(*op=='+')*v+=n;else if(*op=='-')*v-=n;else if(*op=='*')*v*=n;else if(*op=='/'&&n!=0)*v/=n;else *v=n;*entry=0;if(strcmp(s,"="))*op=*s;else *op=0;}
int main(int argc,char **argv){double value=0;char entry[24]="",op=0,t[2];int bx,by,x,y,i,focus=-1,key=0,mx=0,my=0;unsigned mb=0;if(acc_help(argc,argv,"!CALC","A simple four-function desktop calculator."))return 0;if(!acc_begin(argv[0],"Calculator",0))return 1;bx=(acc_cols-37)/2;by=(acc_rows-21)/2;x=bx+3;y=by+5;acc_box(bx,by,37,21,"Calculator");
 while(key!=27){output_box(x,by+2,31,value,entry);draw_keys(x,y,focus);acc_button(bx+3,by+18,"  C  ",focus==17);acc_button(bx+10,by+18,"  CE  ",focus==18);acc_button(bx+27,by+18,"  Close  ",focus==19);acc_wait(&key,&mx,&my,&mb);
  if((mb&1)&&my>=y&&my<y+12&&mx>=x&&mx<x+31){for(i=0;i<17;i++){int xx=x+kx[i],yy=y+ky[i],w=5,h=3;if(i==3||i==12)h=6;if(i==14)w=11;if(mx>=xx&&mx<xx+w&&my>=yy&&my<yy+h){focus=i;apply(keys[i],&value,entry,&op);break;}}key=0;continue;}if((mb&1)&&my==by+18){if(mx>=bx+3&&mx<bx+8){focus=17;value=0;entry[0]=op=0;key=0;continue;}else if(mx>=bx+10&&mx<bx+16){focus=18;entry[0]=0;key=0;continue;}else if(mx>=bx+28&&mx<bx+34){focus=19;key=27;continue;}}
  if(key==9){focus=focus<0?0:(focus+1)%20;key=0;}else if(focus<17&&(key==256+75||key==256+77||key==256+72||key==256+80)){focus=move_key(focus,key);key=0;}else if(key==13){flash_key(x,y,16,focus);apply("=",&value,entry,&op);key=0;}else if(key=='c'||key=='C'){value=0;entry[0]=op=0;key=0;}else if(key=='e'||key=='E'||key==256+83){entry[0]=0;key=0;}else if(key==' '&&focus>=0){if(focus==17){value=0;entry[0]=op=0;}else if(focus==18)entry[0]=0;else if(focus==19)key=27;else{flash_key(x,y,focus,focus);apply(keys[focus],&value,entry,&op);}if(key!=27)key=0;}else if(key==8&&*entry){entry[strlen(entry)-1]=0;key=0;}else if((key>='0'&&key<='9')||key=='.'||key=='+'||key=='-'||key=='*'||key=='/'||key=='%'||key=='='){int ki=key_index(key);t[0]=(char)key;t[1]=0;flash_key(x,y,ki,focus);apply(t,&value,entry,&op);key=0;}else if(key!=27)key=0;
 }acc_end();return 0;}
