#ifndef LAUNCH_SAVERS_H
#define LAUNCH_SAVERS_H

void abstractile_saver_loop(unsigned start_x,unsigned start_y);
void blaster_saver_loop(unsigned start_x,unsigned start_y);
void rocks_saver_loop(unsigned start_x,unsigned start_y);
void scooter_saver_loop(unsigned start_x,unsigned start_y);
void squiral_saver_loop(unsigned start_x,unsigned start_y);
void splotchy_saver_loop(unsigned start_x,unsigned start_y);

#endif
